/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package search;

import com.sun.corba.se.impl.orbutil.closure.Constant;
import indexing.BuildIndex;

import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import org.apache.lucene.document.Document;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.search.ScoreDoc;
import org.apache.lucene.search.TopDocs;
import utility.CONSTANTS;
import utility.FileContent;
import utility.WriteVariousStatistics;

/**
 *
 * @author mdkamruzzamansarker checking git commits
 */
public class SearchGUI extends javax.swing.JFrame {

	private String inputquery = null;
	private static JLabel[] resultlabels = new JLabel[10];

	private final String APP_TITLE = "Naive Search Engine";
	private final String SEARCH_BUTTON_TEXT = "Search";
	private JPanel searchInputPanel;
	private JPanel searchResultPanel;
	private JPanel searchStatusPanel;
	private JButton searchButton;
	private JTextArea searchInputTextArea;

	private ActionListener searchActionListener;

	/**
	 * Creates new form JavaApplication1GUI
	 */
	public SearchGUI() {
		//initComponents();
		initComponentsCustom();
	}

	private void initComponentsCustom() {
		setTitle(APP_TITLE);
		setLayout(new BorderLayout());
		setSize(700, 500);

		searchInputPanel = new JPanel();
		searchInputPanel.setLayout(new BorderLayout());
		searchButton = new JButton(SEARCH_BUTTON_TEXT);
		searchButton.addActionListener(new SearchActionListener());
		searchButton.setPreferredSize(new Dimension(100,20));
		searchButton.setSize(new Dimension(100,20));
		
		searchInputTextArea = new JTextArea();
		searchInputTextArea.setLineWrap(true);
		searchInputTextArea.setRows(1);
		
		searchInputPanel.add(searchButton, BorderLayout.EAST);
		searchInputPanel.add(searchInputTextArea, BorderLayout.CENTER);
		
		
		add(searchInputPanel, BorderLayout.NORTH);

	}

	private class SearchActionListener implements ActionListener {

		public SearchActionListener() {

		}

		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub

		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		resultPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		searchPanel = new javax.swing.JPanel();
		jTextArea1 = new javax.swing.JTextArea();
		btnSearch = new javax.swing.JButton();
		lblTotal = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setLocation(new java.awt.Point(0, 0));
		setName("mainframe"); // NOI18N

		resultPanel
				.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 204)));
		resultPanel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

		javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
		resultPanel.setLayout(resultPanelLayout);
		resultPanelLayout
				.setHorizontalGroup(
						resultPanelLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										resultPanelLayout.createSequentialGroup().addGap(28, 28, 28)
												.addGroup(
														resultPanelLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jLabel9).addComponent(jLabel10)
																.addComponent(jLabel8).addComponent(jLabel7)
																.addComponent(jLabel6).addComponent(jLabel5)
																.addComponent(jLabel4).addComponent(jLabel3)
																.addComponent(jLabel2).addComponent(jLabel1))
												.addContainerGap(371, Short.MAX_VALUE)));
		resultPanelLayout.setVerticalGroup(resultPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(resultPanelLayout.createSequentialGroup().addGap(16, 16, 16)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel7)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel8)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
						.addComponent(jLabel9).addGap(18, 18, 18).addComponent(jLabel10,
								javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		getContentPane().add(resultPanel, java.awt.BorderLayout.CENTER);

		searchPanel.setLayout(new java.awt.BorderLayout());

		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(1);
		jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		searchPanel.add(jTextArea1, java.awt.BorderLayout.NORTH);

		btnSearch.setText("Search");
		btnSearch.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});
		searchPanel.add(btnSearch, java.awt.BorderLayout.EAST);
		searchPanel.add(lblTotal, java.awt.BorderLayout.WEST);

		getContentPane().add(searchPanel, java.awt.BorderLayout.PAGE_START);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// String abc = "abc";
	// resultlabels[0] = new JLabel();
	// resultlabels[0].setText("<html><a href=" + abc + ">link</a></html>.");
	//

	// resultPanel.revalidate();
	// validate();

	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearchActionPerformed

		// Split CranfieldMain Data Set
		// callSplitter();
		int totalDocsFound = 0;

		Controller controller = new Controller();

		inputquery = jTextArea1.getText();
		if (inputquery != null) {
			try {

				long startTime = System.nanoTime();
				totalDocsFound = controller.search(inputquery);
				long endTime = System.nanoTime();

				CONSTANTS.totalduration = (endTime - startTime) / 1000000; // divide
																			// by
																			// 1000000
																			// to
																			// get
																			// milliseconds.

				lblTotal.setText("Total found in: " + totalDocsFound + " documents.");
				// jLabel1.setText(inputquery);
				// Show Result
				WriteVariousStatistics w = new WriteVariousStatistics();
				w.writeCalcTimes();

			} catch (IOException ex) {
				Logger.getLogger(SearchGUI.class.getName()).log(Level.SEVERE, null, ex);
			} catch (ParseException ex) {
				Logger.getLogger(SearchGUI.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			System.out.println("Input is null");
		}
		// from here copied
	}// GEN-LAST:event_btnSearchActionPerformed

	private void callSplitter() {
		JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor((SearchGUI) this);
		try {
			FileContent.chooseFile(topFrame);
		} catch (Exception ex) {
			Logger.getLogger(SearchGUI.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new SearchGUI().setVisible(true);

					CONSTANTS.OSName = System.getProperty("os.name");

					// Build Index
//					String path = getClass().getClassLoader().getResource(CONSTANTS.indexpath).getPath();
//					if (CONSTANTS.OSName.startsWith("Win")) {
//						path = path.substring(1, path.length());
//					}
//					if (!(Files.exists(Paths.get(path + "/_0.cfe")))) {
//						new BuildIndex();
//					}
				} catch (Exception ex) {
					Logger.getLogger(SearchGUI.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSearch;
	protected javax.swing.JLabel jLabel1;
	protected javax.swing.JLabel jLabel10;
	protected javax.swing.JLabel jLabel2;
	protected javax.swing.JLabel jLabel3;
	protected javax.swing.JLabel jLabel4;
	protected javax.swing.JLabel jLabel5;
	protected javax.swing.JLabel jLabel6;
	protected javax.swing.JLabel jLabel7;
	protected javax.swing.JLabel jLabel8;
	protected javax.swing.JLabel jLabel9;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JLabel lblTotal;
	protected javax.swing.JPanel resultPanel;
	private javax.swing.JPanel searchPanel;
	// End of variables declaration//GEN-END:variables
}
